version: "3.7"
services:

  moinmoin:
    container_name: moinmoin
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: twotwo/moinmoin:1.9.10
    # # docker stack deploy -c docker-compose.yml wiki
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    environment:
      - MOIN_DEBUG=1 # Debug mode - show detailed error reports
      - MOIN_DEBUG_LOGDIR=/var/www/moin/var/debug #https://moinmo.in/UsefulErrors
    ports:
      - 3301:3301
    networks:
      - wiki
    volumes:
      - "moin_data:/srv/www/moin"
    restart: on-failure

networks:
  wiki:

volumes:
  moin_data:
    driver: local