version: "3.7"
services:

  moinmoin:
    container_name: moinmoin
    build:
      context: ./
      dockerfile: Dockerfile-gunicorn
    image: twotwo/moinmoin
    # # docker stack deploy -c docker-compose.yml wiki
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    ports:
      - 3301:3301
    networks:
      - wiki
    volumes:
      - "/srv/www/moin:/srv/www/moin"
    restart: on-failure

networks:
  wiki: